#!/bin/bash
helpNetflix ()
{
  echo "Usage: netflix <search>"
  echo "Example: netflix \"Food Wars\""
  echo "Ne supporte pas les caractères spéciaux, utiliser [A-Za-z1-0]* ou l'espace"
}

if [ "$1" = "-h" ]
then
  helpNetflix
elif [ -z "$1" ]
then
  helpNetflix
else
  killall firefox-esr > /dev/null
  firefox "https://www.netflix.com/search?q=$1" &
  echo "Attente ouverture firefox..."
  sleep 8
  echo "Injection JS..."
  xdotool key ctrl+shift+k
  sleep 2
  xdotool type --delay 60 "while (\$('.profile-link')==null){i=0;}if(\$('.slider-refocus')==null){\$('.profile-link').click()}while(\$('.slider-refocus')==null){i=1;}elt=document.getElementsByClassName('slider-refocus');for(i=0;i<elt.length;++i){if(elt[i].href && elt[i].text.toLowerCase().includes(\""
  xdotool type --delay 60 "$1"
  xdotool type --delay 60 "\".toLowerCase()))window.location=elt[i].href}"
  xdotool key Return
  sleep 5
  xdotool key F12
  xdotool key F11
fi
