#!/bin/sh
if [ "$1" = "+" ];then
  xdotool key XF86AudioRaiseVolume
fi
if [ "$1" = "-" ];then
  xdotool key XF86AudioLowerVolume
fi
if [ "$1" = "0" ];then
  xdotool key XF86AudioLowerVolume
  xdotool key XF86AudioLowerVolume
  xdotool key XF86AudioLowerVolume
  xdotool key XF86AudioLowerVolume
  xdotool key XF86AudioLowerVolume
  xdotool key XF86AudioLowerVolume
  xdotool key XF86AudioLowerVolume
  xdotool key XF86AudioLowerVolume
  xdotool key XF86AudioLowerVolume
  xdotool key XF86AudioLowerVolume
  xdotool key XF86AudioLowerVolume
fi
